Vagrant.configure("2") do |config|
  config.vm.define "controller" do |controller|
    controller.vm.provider "virtualbox" do |this_vm|
      this_vm.gui = false
      this_vm.cpus = 2
      this_vm.name = "controller"
      this_vm.memory = "1024"
    end
    controller.vm.box = "centos/8"
    controller.vm.network "private_network", ip: "192.168.11.100"
  end
  config.vm.define "server1" do |server1|
    server1.vm.provider "virtualbox" do |this_vm|
      this_vm.gui = false
      this_vm.cpus = 2
      this_vm.name = "server1"
      this_vm.memory = "1024"
    end
    server1.vm.box = "centos/8"
    server1.vm.network "private_network", ip: "192.168.10.101"
  end
  config.vm.define "server2" do |server2|
    server2.vm.provider "virtualbox" do |this_vm|
      this_vm.gui = false
      this_vm.cpus = 2
      this_vm.name = "server2"
      this_vm.memory = "1024"
    end
    server2.vm.box = "centos/8"
    server2.vm.network "private_network", ip: "192.168.10.102"
  end
  config.vm.define "server3" do |server3|
    server3.vm.provider "virtualbox" do |this_vm|
      this_vm.gui = false
      this_vm.cpus = 2
      this_vm.name = "server3"
      this_vm.memory = "1024"
    end
    server3.vm.box = "centos/8"
    server3.vm.network "private_network", ip: "192.168.10.103"
  end
end